"""XDG Base Directory resolution for lanista.

Layout:
    $XDG_CONFIG_HOME/lanista/
        sources/          # curated and manual-drop source blobs (hand-editable)
            gkisokay.json
            artificial_analysis.json    (optional, user-populated)
        aliases.json      # model-id canonicalization table

    $XDG_CACHE_HOME/lanista/
        sources/          # auto-fetched source blobs (regenerable)
            openrouter.json
            litellm.json
            pimono.json
            factory_weather.json
            aider.json
        model_index.json  # merged index

Config-dir files are persistent and user-editable. Cache-dir files are
regenerated by ``lanista fetch`` and safe to delete.
"""

from __future__ import annotations

import os
from pathlib import Path

APP_NAME = "lanista"


def _xdg_dir(env_var: str, default_subdir: str) -> Path:
    value = os.environ.get(env_var)
    if value:
        return Path(value)
    return Path.home() / default_subdir


def config_dir() -> Path:
    return _xdg_dir("XDG_CONFIG_HOME", ".config") / APP_NAME


def cache_dir() -> Path:
    return _xdg_dir("XDG_CACHE_HOME", ".cache") / APP_NAME


def sources_config_dir() -> Path:
    """Curated / manual-drop source blobs. User-editable, persistent."""
    return config_dir() / "sources"


def sources_cache_dir() -> Path:
    """Auto-fetched source blobs. Regenerated by ``lanista fetch``."""
    return cache_dir() / "sources"


def aliases_path() -> Path:
    return config_dir() / "aliases.json"


def index_path() -> Path:
    return cache_dir() / "model_index.json"


def source_path(name: str, curated: bool = False) -> Path:
    """Path for a single source blob, by convention ``<name>.json``."""
    base = sources_config_dir() if curated else sources_cache_dir()
    return base / f"{name}.json"


def ensure_parent(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path
